### PR TITLE
feat: add status codes from RFC 8132

### PR DESCRIPTION
**Pull request by JKRhb**
This PR adds the status codes that have been introduced in [RFC 8132](https://datatracker.ietf.org/doc/html/rfc8132#section-3.4) to the module. This enables other projects like `node-coap` to add support for the FETCH, PATCH, and iPATCH methods.

### CODE REVIEW

**Comment by JKRhb** [comment]
@mcollina Could you maybe have a quick look on this PR? :) I need the status codes for https://github.com/mcollina/node-coap/pull/264

**Comment by mcollina** [comment]
I think this module needs quite a lot of maintenenace before adding new features.

Could you:

1. update it to github actions
2. update all dependencies

In a fresh PR?

**Comment by JKRhb** [comment]
> I think this module needs quite a lot of maintenenace before adding new features.
> 
> Could you:
> 
> 1. update it to github actions
> 2. update all dependencies
> 
> In a fresh PR?

Sure, will do :) I'll ping you once it's ready

**Comment by JKRhb** [comment]
@mcollina I've opened #13 now to address the dependency and CI issue

**Comment by JKRhb** [comment]
@mcollina I have now made the coveralls step optional so that the CI does not fail when the upload isn't successful. This way the functionality can simply be added later and we can proceed with merging.

**Comment by JKRhb** [comment]
After the merging of #15, this PR is now obsolete.

**Pull request closed without merging**
